# Generated by Django 3.0 on 2020-08-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200801_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
