# Generated by Django 3.0 on 2020-08-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200802_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
