# Generated by Django 3.0.3 on 2020-04-05 16:58

from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(default='john-schnobrich-FlPc9_VocJ4-unsplash.jpg', upload_to=job.models.image_name)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='Job Description ')),
                ('job_image', models.ImageField(upload_to=job.models.get_image_filename, verbose_name='Company Image')),
                ('job_location_place', models.CharField(max_length=50, verbose_name='Job Location Place')),
                ('about_company', models.TextField(verbose_name='About Company')),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('post_date', models.DateField(verbose_name='Post Date')),
                ('last_date_apply_by', models.DateField(verbose_name='Last Date Apply By')),
                ('skills_required', models.TextField(verbose_name='Skills Required')),
                ('who_can_apply', models.TextField(verbose_name='Who Can Apply')),
                ('other_requirments', models.CharField(max_length=100, verbose_name='Other Requirments')),
                ('salary', models.FloatField(default=0, verbose_name='Salary')),
                ('createation_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
            ],
        ),
    ]
