# Generated by Django 3.0 on 2020-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mobile_number',
            field=models.CharField(default=0, max_length=12, verbose_name='Mobile No.'),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_openings',
            field=models.IntegerField(default=0, max_length=1000, verbose_name='Number Of Openings'),
        ),
    ]
